Repository projectsyn/component-cert-manager, pull requests merged in 2022-04, with the labels that each got.

#73 Move postprocessing filter definitions to component class
  class/cert-manager.yml
  postprocess/filters.yml
Labels: change

#74 Rename the helm chart release_name variable for Kapitan to name
  class/cert-manager.yml
Labels: dependency

#75 Upgrade to cert-manager v1.5.5
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/cainjector-deployment.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/cainjector-rbac.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/cainjector-serviceaccount.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/crds.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/deployment.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/rbac.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/service.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/serviceaccount.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/servicemonitor.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/startupapicheck-job.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/startupapicheck-rbac.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/startupapicheck-serviceaccount.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/webhook-deployment.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/webhook-mutating-webhook.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/webhook-rbac.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/webhook-service.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/webhook-serviceaccount.yaml
  tests/golden/defaults/cert-manager/cert-manager/01_helmchart/cert-manager/templates/webhook-validating-webhook.yaml
Labels: dependency

#76 Define code owners
  CODEOWNERS
Labels: documentation

#81 Make acme-dns registration job an ArgoCD sync hook
  component/acme-dns.libsonnet
  tests/golden/defaults/cert-manager/cert-manager/02_issuers/20_acme_dns.yaml
Labels: bug

#80 Change registry for `bitnami/kubectl` to docker.io
  class/defaults.yml
  tests/golden/defaults/cert-manager/cert-manager/02_issuers/20_acme_dns.yaml
  tests/golden/defaults/cert-manager/cert-manager/03_upgrade/00_upgrade.yaml
Labels: dependency

#84 Fix documentation link
  docs/modules/ROOT/partials/nav.adoc
Labels: ignore
