Repository projectsyn/component-cert-manager, pull requests merged in 2025-02, with the labels that each got.

#154 Update quay.io/appuio/oc Docker tag to v4.16
  class/defaults.yml
  tests/golden/defaults/cert-manager/cert-manager/02_issuers/20_acme_dns.yaml
  tests/golden/defaults/cert-manager/cert-manager/03_upgrade/00_upgrade.yaml
Labels: dependency

#166 Change naming scheme of acmedns clients
  component/acme-dns.libsonnet
  component/legacy.libsonnet
  tests/defaults.yml
  tests/golden/defaults/cert-manager/cert-manager/50_acme_dns_acme-dns.yaml
  tests/golden/defaults/cert-manager/cert-manager/50_acme_dns_common.yaml
  tests/golden/legacy/cert-manager/cert-manager/50_acme_dns_acme-dns.yaml
  tests/golden/legacy/cert-manager/cert-manager/50_acme_dns_common.yaml
Labels: change

#165 Refactor issuer configuration
  class/cert-manager.yml
  class/defaults.yml
  component/issuers.jsonnet
  component/issuers.libsonnet
  component/legacy.libsonnet
  component/main.jsonnet
  component/upgrade.jsonnet
  docs/modules/ROOT/pages/how-tos/dns01.adoc
  docs/modules/ROOT/pages/how-tos/http01-ocp.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  lib/cert-manager.libsonnet
  tests/defaults.yml
  tests/golden/defaults/cert-manager/cert-manager/60_clusterissuer.yaml
  tests/golden/defaults/cert-manager/cert-manager/60_issuer.yaml
  tests/golden/legacy/cert-manager/cert-manager/60_clusterissuer.yaml
  tests/golden/legacy/cert-manager/cert-manager/60_issuer.yaml
  tests/legacy.yml
Labels: breaking

#168 Document migration and small fixes
  component/issuers.libsonnet
  docs/modules/ROOT/pages/how-tos/upgrade-v3-v4.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/golden/legacy/cert-manager/cert-manager/60_clusterissuer.yaml
  tests/legacy.yml
Labels: change, bump:major

#170 Fix acmeClient not correctly translated to solver
  component/acme-dns.libsonnet
  component/legacy.libsonnet
  docs/modules/ROOT/pages/how-tos/upgrade-v3-v4.adoc
  tests/defaults.yml
  tests/golden/defaults/cert-manager/cert-manager/60_clusterissuer.yaml
  tests/golden/legacy/cert-manager/cert-manager/60_clusterissuer.yaml
  tests/legacy.yml
Labels: bug, bump:patch

#171 Fix acmeClients precedence over legacy client
  component/legacy.libsonnet
Labels: bug, bump:patch

#174 Patch exoscale-webhook deployment to use container port 8443
  postprocess/patch-exoscale.jsonnet
  tests/golden/defaults/cert-manager/cert-manager/20_exoscale_webhook/exoscale-webhook/templates/deployment.yaml
Labels: bug

#175 Generates acme spec for Let's Encrypt for all Issuers starting with letsencrypt
  component/issuers.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/cert-manager/cert-manager/60_clusterissuer.yaml
Labels: bug, bump:patch
